image: python:3.7.2-stretch

stages:
  - build

pages:
  stage: build
  script:
  - pip install urllib3
  - pip install requests
  - pip install pytz
  - python asm.py
  artifacts:
    paths:
    - public/
  only:
  - master
